name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull Docker Images and Save Directly
      run: |
        mkdir -p docker-images
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        
        # 创建镜像列表文件
        touch docker-images/image-list.txt
        
        for image in "${image_array[@]}"; do
          echo "Pulling and saving: ${image}"
          # 使用简化的镜像名作为文件名
          safe_name=$(echo "${image}" | tr '/:' '_-')
          
          # 直接保存镜像到tar文件
          docker pull "${image}" --platform "linux/amd64"
          docker save "${image}" -o "docker-images/${safe_name}-amd64.tar"
          
          # 记录镜像名到清单文件
          echo "${image}" >> docker-images/image-list.txt
        done

    - name: Upload artifacts directly
      uses: actions/upload-artifact@v4
      with:
        name: docker-images
        path: docker-images/
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天
        
    - name: Clean up files
      run: |
        rm -rf docker-images/
        docker system prune -a -f
